### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by bergus** [wereHamster/haskell-css-syntax#1]
Hi,
is this project still active? Do you plan to include a parser that takes the token stream and spits out a higher-level representation of the CSS?
Btw, I believe there's a "not" missing in "_Parsing the token stream into rules or declarations is available as of yet._" in your readme.

I am looking for a way to find all `@import` declarations in a file, and am not sure how to do that on the token level.

**Comment by wereHamster** [comment]
Not really active but I will respond to bug reports and help anybody who wants to integrate this library into their own project.

I don't plan to work on a higher-level parser (ie. https://www.w3.org/TR/css-syntax-3/#parsing), as I only need the output from the tokenization in my projects.

For your use-case, I think it should be sufficient to look for a `AtKeyword` followed by a `String`. That will catch declarations in the form `@import "..."` (with either single or double quotes).

If you want to support `@import url(...)` it gets a bit more complicated because you have to catch a few more combinations of `AtKeyword` followed by `Url` and `Function`, but it's certainly doable with the functions / types the library currently provides.

**Comment by bergus** [comment]
Yeah, `AtKeyword` followed by a `String`, with `Whitespace`s and possibly even comments in between…
I guess I _could_ do that with parser combinators somehow, and that's only the simple case.
I think I'll still try with regex first (though knowing deep inside it's the wrong tool) :-)

**Comment by bergus** [comment]
OK, it was simpler than I thought:

``` haskell
{-# LANGUAGE ViewPatterns #-} 
expandImportsWith :: Monad m => (FilePath -> m String) -> [Token] -> m String
expandImportsWith load = expandImports []
  where
    output :: [Token] -> String
    output acc = unpack $ serialize $ reverse acc

    expandImports acc [] = return $ output acc
    expandImports acc (AtKeyword (unpack -> "import") : Whitespace : urltoken : ts) = do
      let url = unpack $ case urltoken of
                           BadUrl tUrl   -> tUrl
                           Url tUrl      -> tUrl
                           String _ tUrl -> tUrl
      imported <- load url
      case span (/= Semicolon) ts of
        ([], Semicolon:ts) -> do
          rest <- expandImports [] ts
          return $ output acc ++ imported ++ rest
        (query, Semicolon:ts) -> do
          rest <- expandImports [RightCurlyBracket] ts
          return $ output acc ++ (unpack $ serialize $ (AtKeyword (pack "media") : query ++ [LeftCurlyBracket])) ++ imported ++ rest
    expandImports acc (t:ts) = expandImports (t:acc) ts
```

This thing is called from a [Hakyll Compiler](https://github.com/jaspervdj/hakyll) like so

```
expandCssCompiler :: Compiler (Item String)
expandCssCompiler = getResourceString >>= withItemBody (packCss . compressCss)

packCss :: String -> Compiler String
packCss = either fail (expandImportsWith resolveItem) . tokenize . pack

resolveItem :: FilePath -> Compiler String
resolveItem path = do
  loc <- fmap toFilePath getUnderlying
  let target = interpretPath loc path
  (loadBody $ fromFilePath $ target) `catchError` (\e -> throwError $ ("trying to load "++path++" from "++loc):e)
```

By applying [`compressCss`](https://jaspervdj.be/hakyll/reference/Hakyll-Web-CompressCss.html#v:compressCss) before tokenizing, I don't have to deal with multiple whitespace tokens any more.

I'll leave this here as an example for usage of the library, feel free to criticize.

**Comment by wereHamster** [comment]
Great.

Note that the `Whitespace` token can cover multiple whitespace characters. You won't see multiple consecutive `Whitespace` tokens. What `compressCss` probably will do is remove comments between "@import" and the URL, so you don't have to deal with it in the token stream.

Second note,  `serialize` is probably not as efficient as it could be. For example it will convert all `Whitespace` tokens into a single space character, even if not strictly necessary. So you may want to run the output through `compressCss` again to shave off as many bytes as possible.

**Comment by wereHamster** [comment]
And a third note, this tokenizer strips all comments from the code, you don't have to deal with or worry about comments in your code.

The only thing `compressCss` does which this tokenizer doesn't do is _Compresses certain forms of separators._ (`compressSeparators` function). While that function does some useful compression, I doubt it has high impact on the output size.

**Comment by bergus** [comment]
> Note that the `Whitespace` token can cover multiple whitespace characters. You won't see multiple consecutive `Whitespace` tokens.

I cannot confirm that. I did an intial test (with `show` instead of `serialize`) and saw them, so that's why I cared about them. It seems that when intermitted by comments, the tokenizer generates multiple of them - a mimimal test case:

```
@charset "UTF-8";
/*…*/

/*…*/
@import url(yaml/core/base.css);
```

This yields three consecutive `Whitespace`s.

> And a third note, this tokenizer strips all comments from the code, you don't have to deal with or worry about comments in your code.

I figured that out by now :-) I wonder though what purpose the `CDO` and `CDC` tokens have? Does the CSS spec require to take HTML-style comments into consideration?
Actually I'd loved if the tokenizer did keep comments as tokens. It's relatively trivial to `filter` them out, and they could prove quite useful if you want to insert text manually into the stream (debugging, visual segmentation, intro, outro).

**Comment by wereHamster** [comment]
If the tokenizer generates multiple consecutive `Whitespace` tokens, I'd consider that a bug :) An easy one to fix.

As for CDO/CDC, these tokens are in the spec: https://drafts.csswg.org/css-syntax/

**Comment by bergus** [comment]
Ah, I remember now, CDO/CDC is required for the legacy format `<style><!-- … --></style>`, which was needed in the earliest to days of the web to prevent browsers that did not know the `style` element from displaying the stylesheet. That's why these tokens may only appear at top level.

And I just found out that the parsing is not exactly as easy as I thought. It only worked because all of my imports were of the format `import url(…);`. However, the grammar does permit an arbitrary number of whitespaces (including none) between `import` and `url(`, between `url(` and the string/content, the content and the closing parenthesis, as well as the parenthesis and the semicolon. No way I can handle that via pattern matching alone.
Also I just noticed that `url(…)` and `url("…")` return completely different (series of) tokens, so I will need to distinguish that as well. Guess I'll need to put some more work into this :-/

**Comment by wereHamster** [comment]
About `url()`, one is a `Function` token and one is a `Url` token. The spec distinguishes between the two, probably for legacy reasons.

You could handle the extra whitespace with patterns (optional or zero-or-more whitespace character patterns).

**Comment by bergus** [comment]
Did you refer to pattern matching or to parser combinators with the term "patterns"? I guess I'll have to go with the latter, let me know if there is something else.

**Comment by bergus** [comment]
> About  url() , one is a `Function` token and one is a `Url` token. The spec distinguishes between the two, probably for legacy reasons.

Hm, are you sure of that? If I read https://www.w3.org/TR/CSS22/grammar.html correctly, then everything that begins with `url(` is either a `URI` or `BADURI` token.

**Comment by wereHamster** [comment]
I implemented the tokenizer as specified by the CSS Syntax Module Level 3 spec (https://drafts.csswg.org/css-syntax/), not the CSS22 spec.

You also see it in the tests, which I copied from the Chromium repository: https://github.com/wereHamster/haskell-css-syntax/blob/e830288dc620b6b1d1afbfe74a90328b00b5dd5b/test/Test.hs#L108 and https://github.com/wereHamster/haskell-css-syntax/blob/e830288dc620b6b1d1afbfe74a90328b00b5dd5b/test/Test.hs#L128-L147

**Comment by wereHamster** [comment]
I don't see how the css-syntax-3 spec allows no whitespace between "@import" and the url. "@importurl" would be a totally different at-keyword-token. Anyway, now we only have to deal with consecutive whitespace tokens, which are relatively easy to remove.

You can extract all tokens between "@import" and the next semicolon, remove all whitespace and then see what's left (and hope that it's function-token or url-token). In the absence of a real parser (https://drafts.csswg.org/css-syntax/#parsing), all you do will be an approximation and you may miss some weird edge-cases.

**Comment by bergus** [comment]
Ah, [I see now](https://drafts.csswg.org/css-syntax/#consume-an-ident-like-token).
Btw, I found that a [BadToken](https://drafts.csswg.org/css-syntax/#typedef-bad-url-token) does not have a value attached, so I can probably drop that from my matches.

> I don't see how the css-syntax-3 spec allows no whitespace between "@import" and the url

I was thinking of `@import"mystyle.css"` :-)

> In the absence of a real parser all you do will be an approximation and you may miss some weird edge-cases.

Actually I am thinking of writing one now :-P But I'm pretty sure the Parsec parser I've written now does catch all edge cases in valid stylesheets (It does not check for import declarations to be in the wrong place however).
