### ISSUE TITLE
Please publish fixes to support Text v2 to Hackage

### ISSUE THREAD

**Issue by alcinnz** [wereHamster/haskell-css-syntax#5]
I've been making great use of your CSS lexer to develop my own (now NLnet-funded) browser engine, & am very grateful for your work. Thank you!

But now I've got another component depending on Text v2 (which has switched from UTF-16 to UTF-8 native encoding), leading to a dependency clash holding me up from publishing a component. You've recently accepted a pull request addressing this, but the changes are not yet on Hackage.

I am willing to take over this project if you need?

**Comment by alcinnz** [comment]
In doing some additional testing, I noticed that the version on Hackage doesn't build under base-4.15 but the version on GitHub does. This is another reason for me to strongly request that a new release be published.

Need help? I have heavily benefited from this code, and would hate to see it die!

**Comment by alcinnz** [comment]
I've now been granted access as co-maintainer on Hackage & have released the latest changes you've pulled to be compatible with Text v2.

I'd appreciate hearing how you'd like to manage this between the two of us? And will gladly step aside if you wish to be more active. Until then I'm happy releasing any updates made in this GitHub repository.

**Comment by wereHamster** [comment]
I invited you as collaborator to this repo.

**Comment by wereHamster** [comment]
Feel free to push changes, and release on Hackage on your own.

**Comment by wereHamster** [comment]
I also invited @vshabanov …

**Comment by alcinnz** [comment]
Thanks!

**Comment by vshabanov** [comment]
Thank you both! Glad to finally see it on Hackage.
